"use client";

import React from "react";
import useSWR from "swr";
import { 
  Cpu, 
  Trash2, 
  Code,
  Search,
  X,
  FileCode,
  Calendar,
  AlertCircle
} from "lucide-react";
import { PageHeader } from "../_components/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

interface Workflow {
  _id: string;
  title: string;
  description: string;
  script: string;
  createdAt: string;
}

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function WorkflowsPage() {
  const [searchQuery, setSearchQuery] = React.useState("");
  const [selectedWorkflow, setSelectedWorkflow] = React.useState<Workflow | null>(null);

  const { data: result, isLoading, mutate } = useSWR("/api/workflows", fetcher);
  const workflows = React.useMemo(() => result?.data || [], [result]);

  const filteredWorkflows = React.useMemo(() => {
    if (!searchQuery.trim()) return workflows;
    const q = searchQuery.toLowerCase();
    return workflows.filter((w: Workflow) => 
      w.title.toLowerCase().includes(q) || 
      w.description.toLowerCase().includes(q)
    );
  }, [workflows, searchQuery]);

  const handleDelete = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!window.confirm("Are you sure you want to delete this workflow?")) return;

    try {
      const res = await fetch(`/api/workflows/${id}`, { method: "DELETE" });
      const data = await res.json();
      if (data.success) {
        toast.success("Workflow deleted successfully");
        mutate();
        if (selectedWorkflow?._id === id) {
          setSelectedWorkflow(null);
        }
      } else {
        toast.error(data.error || "Failed to delete workflow");
      }
    } catch (err) {
      toast.error("Failed to delete workflow");
    }
  };

  return (
    <div className="flex h-screen relative overflow-hidden bg-app-canvas text-app-text-primary">
      <div className="flex-1 flex flex-col min-w-0 relative">
        <PageHeader
          icon={<Cpu />}
          title="AI Workflows"
          subtitle="View and manage code workflows generated by Jarvis"
        />

        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Controls */}
          <div className="flex items-center gap-4 max-w-md bg-app-surface-glass border border-app-border-default rounded-xl px-3 py-1.5">
            <Search className="size-4 text-app-text-muted shrink-0" />
            <input
              type="text"
              placeholder="Search workflows..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="bg-transparent border-none outline-none text-sm text-app-text-primary placeholder:text-app-text-muted w-full"
            />
            {searchQuery && (
              <button onClick={() => setSearchQuery("")} className="text-app-text-muted hover:text-app-text-primary">
                <X className="size-4" />
              </button>
            )}
          </div>

          {/* Workflow List */}
          {isLoading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {[1, 2, 3].map((i) => (
                <div key={i} className="h-44 rounded-2xl bg-app-surface-glass border border-app-border-default animate-pulse p-5 space-y-3">
                  <div className="h-6 bg-app-surface-glass rounded w-3/4" />
                  <div className="h-4 bg-app-surface-glass rounded w-5/6" />
                  <div className="h-4 bg-app-surface-glass rounded w-1/2" />
                </div>
              ))}
            </div>
          ) : filteredWorkflows.length === 0 ? (
            <div className="flex flex-col items-center justify-center p-12 text-center bg-app-surface-glass border border-app-border-default rounded-2xl max-w-2xl mx-auto space-y-4">
              <div className="size-12 rounded-xl bg-app-surface-glass-strong border border-app-border-default flex items-center justify-center text-app-text-muted">
                <AlertCircle className="size-6" />
              </div>
              <div>
                <h3 className="text-base font-semibold">No workflows found</h3>
                <p className="text-sm text-app-text-muted mt-1">
                  Ask Jarvis in the chat to create a workflow for you (e.g. "Create a workflow to like a YouTube video").
                </p>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredWorkflows.map((workflow: Workflow) => (
                <div
                  key={workflow._id}
                  onClick={() => setSelectedWorkflow(workflow)}
                  className="group relative rounded-2xl bg-app-surface-glass border border-app-border-default p-5 hover:bg-app-surface-glass-strong cursor-pointer transition-all duration-300 flex flex-col justify-between h-44 shadow-lg hover:shadow-xl"
                >
                  <div className="space-y-2">
                    <div className="flex items-start justify-between">
                      <h3 className="font-bold text-app-text-primary text-base truncate pr-6 group-hover:text-indigo-200 transition-colors">
                        {workflow.title}
                      </h3>
                      <button
                        onClick={(e) => handleDelete(workflow._id, e)}
                        className="opacity-0 group-hover:opacity-100 p-1.5 text-app-text-muted hover:text-app-danger-strong hover:bg-app-danger-soft rounded-lg transition-all absolute right-4 top-4"
                        title="Delete workflow"
                      >
                        <Trash2 className="size-4" />
                      </button>
                    </div>
                    <p className="text-sm text-app-text-muted line-clamp-3">
                      {workflow.description || "No description provided."}
                    </p>
                  </div>
                  <div className="flex items-center gap-4 text-xs text-app-text-faint pt-2">
                    <span className="flex items-center gap-1">
                      <Code className="size-3.5" />
                      JS Code
                    </span>
                    <span className="flex items-center gap-1">
                      <Calendar className="size-3.5" />
                      {new Date(workflow.createdAt).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Detail Modal Side-panel */}
      {selectedWorkflow && (
        <div className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-sm animate-fade-in">
          <div className="fixed inset-0" onClick={() => setSelectedWorkflow(null)} />
          <div className="relative w-full max-w-2xl h-screen bg-app-canvas border-l border-app-border-default flex flex-col shadow-2xl z-10 animate-slide-in">
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-app-border-default shrink-0">
              <div className="flex items-center gap-3">
                <div className="size-9 rounded-xl border border-app-border-default bg-app-surface-glass flex items-center justify-center">
                  <FileCode className="size-4 text-indigo-200" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-app-text-primary">{selectedWorkflow.title}</h2>
                  <span className="text-xs text-app-text-faint">
                    Created on {new Date(selectedWorkflow.createdAt).toLocaleString()}
                  </span>
                </div>
              </div>
              <button
                onClick={() => setSelectedWorkflow(null)}
                className="p-1.5 text-app-text-muted hover:text-app-text-primary hover:bg-app-surface-glass rounded-lg transition-all"
              >
                <X className="size-5" />
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              {selectedWorkflow.description && (
                <div className="space-y-1.5">
                  <h4 className="text-xs font-semibold text-app-text-faint uppercase tracking-wider">Description</h4>
                  <p className="text-sm text-app-text-secondary leading-relaxed bg-app-surface-glass border border-app-border-default p-4 rounded-xl">
                    {selectedWorkflow.description}
                  </p>
                </div>
              )}

              <div className="space-y-2 flex flex-col h-[calc(100%-120px)] min-h-[400px]">
                <h4 className="text-xs font-semibold text-app-text-faint uppercase tracking-wider">Workflow Script</h4>
                <div className="flex-1 bg-zinc-950 border border-app-border-default rounded-xl p-4 overflow-auto font-mono text-xs text-zinc-300 relative group">
                  <button 
                    onClick={() => {
                      navigator.clipboard.writeText(selectedWorkflow.script);
                      toast.success("Script copied to clipboard");
                    }}
                    className="absolute right-4 top-4 px-2.5 py-1.5 text-[10px] bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded border border-zinc-700 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    Copy Code
                  </button>
                  <pre className="whitespace-pre-wrap">{selectedWorkflow.script}</pre>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
